#!/usr/bin/env bash
# To run: 
#   bash < <(curl -s https://github.com/$author_name/$base_name/raw/$tag/install)

base_name=eyelet
author_name=ohrite
git_url=git://github.com/$author_name/$base_name.git
https_url=https://github.com/$author_name/$base_name.git
install_path=$HOME/.$base_name
tag=latest-stable

function show_usage () {
  cat <<USAGE
usage: $0 options

Install eyelet 

OPTIONS
    -t|--tag   TAG  Install a specific tag (by name or SHA) from github
    -h|--help       Display this message
USAGE
}

function git_fetch () {
  which git>/dev/null || exit 1
  
  if [[ ! -d $install_path ]]; then
    if ! git clone $git_url $install_path > /dev/null 2>&1; then
      echo "Unable to clone $git_url, trying https"
      if ! git clone $https_url $install_path > /dev/null 2>&1; then
        echo "Unable to clone $https_url"
        exit 1
      fi
    fi
  fi
  
  builtin cd $install_path

  if ! git checkout $tag > /dev/null 2>&1; then
    echo "Unable to checkout $tag"
    exit 1
  fi
  
  if ! git pull --rebase origin $tag > /dev/null 2>&1; then
    echo "Unable to pull $base_name to latest $tag"
    exit 1
  else
    echo "Pulled $base_name from latest $tag"
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      show_usage
      exit 0
      ;;
    -t|--tag)
      if [[ -n "${2:-}" ]] ; then
        tag="$2"
        shift
      else
        echo "$1 must be followed by a tag."
        exit 1
      fi
      ;;
    *)
      show_usage
      exit 1
      ;;
  esac
  shift
done

git_fetch
